import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "@/Components/Nav";
import { ToastContainer } from "react-toastify";

const montserrat = Montserrat({

  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserrat.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Nav></Nav>
       <main>
         {children}
         <ToastContainer></ToastContainer>
       </main>
        </body>
    </html>
  );
}
